// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8HZj9eUyYw_f9fFW1flbRUrTwxJVwQCc',
    appId: '1:618432448422:web:a05a5222c7270a2f163167',
    messagingSenderId: '618432448422',
    projectId: 'simple-app-18c37',
    authDomain: 'simple-app-18c37.firebaseapp.com',
    storageBucket: 'simple-app-18c37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwnwGtlS91_MTPyLv070sOxK8yJTl8ag4',
    appId: '1:618432448422:android:0ccaac5b65937bf0163167',
    messagingSenderId: '618432448422',
    projectId: 'simple-app-18c37',
    storageBucket: 'simple-app-18c37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdUFHBDFE934laWEfG7sv430ashVzXdSA',
    appId: '1:618432448422:ios:d2071dbfc242ce61163167',
    messagingSenderId: '618432448422',
    projectId: 'simple-app-18c37',
    storageBucket: 'simple-app-18c37.firebasestorage.app',
    iosBundleId: 'com.example.appSimple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdUFHBDFE934laWEfG7sv430ashVzXdSA',
    appId: '1:618432448422:ios:d2071dbfc242ce61163167',
    messagingSenderId: '618432448422',
    projectId: 'simple-app-18c37',
    storageBucket: 'simple-app-18c37.firebasestorage.app',
    iosBundleId: 'com.example.appSimple',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8HZj9eUyYw_f9fFW1flbRUrTwxJVwQCc',
    appId: '1:618432448422:web:2954d9891cec033c163167',
    messagingSenderId: '618432448422',
    projectId: 'simple-app-18c37',
    authDomain: 'simple-app-18c37.firebaseapp.com',
    storageBucket: 'simple-app-18c37.firebasestorage.app',
  );
}
